//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_HouseWeb.UserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFKostService")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthdateUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Card_numberUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Card_typeUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressUser {
            get {
                return this.AddressUserField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressUserField, value) != true)) {
                    this.AddressUserField = value;
                    this.RaisePropertyChanged("AddressUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthdateUser {
            get {
                return this.BirthdateUserField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthdateUserField, value) != true)) {
                    this.BirthdateUserField = value;
                    this.RaisePropertyChanged("BirthdateUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Card_numberUser {
            get {
                return this.Card_numberUserField;
            }
            set {
                if ((object.ReferenceEquals(this.Card_numberUserField, value) != true)) {
                    this.Card_numberUserField = value;
                    this.RaisePropertyChanged("Card_numberUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Card_typeUser {
            get {
                return this.Card_typeUserField;
            }
            set {
                if ((object.ReferenceEquals(this.Card_typeUserField, value) != true)) {
                    this.Card_typeUserField = value;
                    this.RaisePropertyChanged("Card_typeUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailUser {
            get {
                return this.EmailUserField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailUserField, value) != true)) {
                    this.EmailUserField = value;
                    this.RaisePropertyChanged("EmailUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDUser {
            get {
                return this.IDUserField;
            }
            set {
                if ((object.ReferenceEquals(this.IDUserField, value) != true)) {
                    this.IDUserField = value;
                    this.RaisePropertyChanged("IDUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameUser {
            get {
                return this.NameUserField;
            }
            set {
                if ((object.ReferenceEquals(this.NameUserField, value) != true)) {
                    this.NameUserField = value;
                    this.RaisePropertyChanged("NameUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordUser {
            get {
                return this.PasswordUserField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordUserField, value) != true)) {
                    this.PasswordUserField = value;
                    this.RaisePropertyChanged("PasswordUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumberUser {
            get {
                return this.PhoneNumberUserField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberUserField, value) != true)) {
                    this.PhoneNumberUserField = value;
                    this.RaisePropertyChanged("PhoneNumberUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getUser", ReplyAction="http://tempuri.org/IUserService/getUserResponse")]
        Rent_HouseWeb.UserService.UserInfo[] getUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getUserFromID", ReplyAction="http://tempuri.org/IUserService/getUserFromIDResponse")]
        Rent_HouseWeb.UserService.UserInfo[] getUserFromID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/getUserFromName", ReplyAction="http://tempuri.org/IUserService/getUserFromNameResponse")]
        Rent_HouseWeb.UserService.UserInfo[] getUserFromName(string nama);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/loginUser", ReplyAction="http://tempuri.org/IUserService/loginUserResponse")]
        Rent_HouseWeb.UserService.UserInfo[] loginUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/insertUser", ReplyAction="http://tempuri.org/IUserService/insertUserResponse")]
        string insertUser(Rent_HouseWeb.UserService.UserInfo data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/updateUser", ReplyAction="http://tempuri.org/IUserService/updateUserResponse")]
        string updateUser(Rent_HouseWeb.UserService.UserInfo data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : Rent_HouseWeb.UserService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<Rent_HouseWeb.UserService.IUserService>, Rent_HouseWeb.UserService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rent_HouseWeb.UserService.UserInfo[] getUser() {
            return base.Channel.getUser();
        }
        
        public Rent_HouseWeb.UserService.UserInfo[] getUserFromID(string id) {
            return base.Channel.getUserFromID(id);
        }
        
        public Rent_HouseWeb.UserService.UserInfo[] getUserFromName(string nama) {
            return base.Channel.getUserFromName(nama);
        }
        
        public Rent_HouseWeb.UserService.UserInfo[] loginUser(string email, string password) {
            return base.Channel.loginUser(email, password);
        }
        
        public string insertUser(Rent_HouseWeb.UserService.UserInfo data) {
            return base.Channel.insertUser(data);
        }
        
        public string updateUser(Rent_HouseWeb.UserService.UserInfo data) {
            return base.Channel.updateUser(data);
        }
    }
}
