//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_HouseWeb.ReservationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservationInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFKostService")]
    [System.SerializableAttribute()]
    public partial class ReservationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateTimeReservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCustomerReservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDReservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDRoomReservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoReservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameCustomerReservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusReservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipeRoomTypeReservationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateTimeReservation {
            get {
                return this.DateTimeReservationField;
            }
            set {
                if ((object.ReferenceEquals(this.DateTimeReservationField, value) != true)) {
                    this.DateTimeReservationField = value;
                    this.RaisePropertyChanged("DateTimeReservation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCustomerReservation {
            get {
                return this.IDCustomerReservationField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCustomerReservationField, value) != true)) {
                    this.IDCustomerReservationField = value;
                    this.RaisePropertyChanged("IDCustomerReservation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDReservation {
            get {
                return this.IDReservationField;
            }
            set {
                if ((object.ReferenceEquals(this.IDReservationField, value) != true)) {
                    this.IDReservationField = value;
                    this.RaisePropertyChanged("IDReservation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDRoomReservation {
            get {
                return this.IDRoomReservationField;
            }
            set {
                if ((object.ReferenceEquals(this.IDRoomReservationField, value) != true)) {
                    this.IDRoomReservationField = value;
                    this.RaisePropertyChanged("IDRoomReservation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InfoReservation {
            get {
                return this.InfoReservationField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoReservationField, value) != true)) {
                    this.InfoReservationField = value;
                    this.RaisePropertyChanged("InfoReservation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameCustomerReservation {
            get {
                return this.NameCustomerReservationField;
            }
            set {
                if ((object.ReferenceEquals(this.NameCustomerReservationField, value) != true)) {
                    this.NameCustomerReservationField = value;
                    this.RaisePropertyChanged("NameCustomerReservation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusReservation {
            get {
                return this.StatusReservationField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusReservationField, value) != true)) {
                    this.StatusReservationField = value;
                    this.RaisePropertyChanged("StatusReservation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipeRoomTypeReservation {
            get {
                return this.TipeRoomTypeReservationField;
            }
            set {
                if ((object.ReferenceEquals(this.TipeRoomTypeReservationField, value) != true)) {
                    this.TipeRoomTypeReservationField = value;
                    this.RaisePropertyChanged("TipeRoomTypeReservation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservationService.IReservationService")]
    public interface IReservationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/getReservationFromID", ReplyAction="http://tempuri.org/IReservationService/getReservationFromIDResponse")]
        Rent_HouseWeb.ReservationService.ReservationInfo[] getReservationFromID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/insertData", ReplyAction="http://tempuri.org/IReservationService/insertDataResponse")]
        string insertData(Rent_HouseWeb.ReservationService.ReservationInfo data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservationServiceChannel : Rent_HouseWeb.ReservationService.IReservationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationServiceClient : System.ServiceModel.ClientBase<Rent_HouseWeb.ReservationService.IReservationService>, Rent_HouseWeb.ReservationService.IReservationService {
        
        public ReservationServiceClient() {
        }
        
        public ReservationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rent_HouseWeb.ReservationService.ReservationInfo[] getReservationFromID(string id) {
            return base.Channel.getReservationFromID(id);
        }
        
        public string insertData(Rent_HouseWeb.ReservationService.ReservationInfo data) {
            return base.Channel.insertData(data);
        }
    }
}
